# Generated by Django 2.1.1 on 2018-10-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('C', 'Construction'), ('IT', 'Information Technology'), ('I', 'Instrumentation'), ('P', 'Power'), ('PR', 'Printing')], max_length=30)),
                ('year', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth')])),
            ],
        ),
    ]
