# Generated by Django 2.1.1 on 2018-10-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JUAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('sub1', models.CharField(max_length=50)),
                ('sub2', models.CharField(max_length=50)),
                ('sub3', models.CharField(max_length=50)),
                ('sub4', models.CharField(max_length=50)),
                ('sub5', models.CharField(max_length=50)),
                ('sub6', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
