# Generated by Django 2.1.1 on 2018-10-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JUAPP', '0002_auto_20181011_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='year',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], default='First', max_length=10),
        ),
    ]
