# Generated by Django 2.1.1 on 2018-10-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JUAPP', '0003_subjects_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='sub1',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='sub2',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='sub3',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='sub4',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='sub5',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='sub6',
        ),
    ]
