# Generated by Django 2.1.1 on 2018-10-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JUAPP', '0004_auto_20181011_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='dept',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Construction', 'Construction'), ('Power', 'Power'), ('Printing', 'Printing'), ('Instrumentation', 'Instrumentation')], max_length=50),
        ),
    ]
