# Generated by Django 2.1.1 on 2018-10-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JUAPP', '0007_auto_20181011_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
