# Generated by Django 2.1.1 on 2018-10-31 14:05

import JUAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JUAPP', '0009_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='path',
        ),
        migrations.AddField(
            model_name='upload',
            name='resource',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='upload',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to=JUAPP.models.getPath),
        ),
    ]
